---
name: release-please
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: 🚀 release-please
        id: release
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7  # v5
        with:
          release-type: maven
          target-branch: main
